services:
  frontend:
    image: app-image:v1
    ports:
      - "1111:8080"
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: "1"
          memory: 500M
        limits:
          cpus: "2"
          memory: 1000M
    depends_on:
      - devopsdb

  devopsdb:
    image: db-image:v1
    ports:
      - "3306:3306"
    deploy:
      resources:
        reservations:
          cpus: "1"
          memory: 500M
        limits:
          cpus: "2"
          memory: 1000M
    volumes:
      - appdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "devopspassword"

volumes:
  appdata:
